#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18046
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidApp.Resource", IsApplication=true)]

namespace AndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int categories = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int custom_theme_color = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int wa_logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int BackButton = 2131230723;
			
			// aapt resource value: 0x7f080020
			public const int SoundAmplifyingEquipment = 2131230752;
			
			// aapt resource value: 0x7f08003f
			public const int addButton = 2131230783;
			
			// aapt resource value: 0x7f080005
			public const int addressText = 2131230725;
			
			// aapt resource value: 0x7f080013
			public const int awning = 2131230739;
			
			// aapt resource value: 0x7f080038
			public const int back_button = 2131230776;
			
			// aapt resource value: 0x7f080006
			public const int category = 2131230726;
			
			// aapt resource value: 0x7f080036
			public const int content = 2131230774;
			
			// aapt resource value: 0x7f080047
			public const int developerButton = 2131230791;
			
			// aapt resource value: 0x7f080014
			public const int doorMarks = 2131230740;
			
			// aapt resource value: 0x7f080018
			public const int doorWeight = 2131230744;
			
			// aapt resource value: 0x7f080015
			public const int doorWidth = 2131230741;
			
			// aapt resource value: 0x7f08000a
			public const int drive_available = 2131230730;
			
			// aapt resource value: 0x7f080049
			public const int edit_button = 2131230793;
			
			// aapt resource value: 0x7f08001f
			public const int entryPost = 2131230751;
			
			// aapt resource value: 0x7f080026
			public const int evacuation = 2131230758;
			
			// aapt resource value: 0x7f080019
			public const int floor = 2131230745;
			
			// aapt resource value: 0x7f080011
			public const int handle = 2131230737;
			
			// aapt resource value: 0x7f080040
			public const int imageView1 = 2131230784;
			
			// aapt resource value: 0x7f080029
			public const int infoLuminance = 2131230761;
			
			// aapt resource value: 0x7f080028
			public const int infoSigns = 2131230760;
			
			// aapt resource value: 0x7f08002a
			public const int infoVoice = 2131230762;
			
			// aapt resource value: 0x7f080027
			public const int infoWeight = 2131230759;
			
			// aapt resource value: 0x7f080012
			public const int invalidEntry = 2131230738;
			
			// aapt resource value: 0x7f08001e
			public const int invalidManeuver = 2131230750;
			
			// aapt resource value: 0x7f080017
			public const int invalidMove = 2131230743;
			
			// aapt resource value: 0x7f080032
			public const int invalid_eye_availability = 2131230770;
			
			// aapt resource value: 0x7f080033
			public const int invalid_hearing_availability = 2131230771;
			
			// aapt resource value: 0x7f080031
			public const int invalid_move_availability = 2131230769;
			
			// aapt resource value: 0x7f08003c
			public const int itemsList = 2131230780;
			
			// aapt resource value: 0x7f080021
			public const int lift = 2131230753;
			
			// aapt resource value: 0x7f080025
			public const int liftBrail = 2131230757;
			
			// aapt resource value: 0x7f080023
			public const int liftDepth = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int liftDoorWeight = 2131230756;
			
			// aapt resource value: 0x7f080022
			public const int liftWight = 2131230754;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080037
			public const int linearLayout2 = 2131230775;
			
			// aapt resource value: 0x7f080009
			public const int loadPhotoButton = 2131230729;
			
			// aapt resource value: 0x7f080044
			public const int loginButton = 2131230788;
			
			// aapt resource value: 0x7f080041
			public const int loginText = 2131230785;
			
			// aapt resource value: 0x7f080004
			public const int nameText = 2131230724;
			
			// aapt resource value: 0x7f08003a
			public const int next_button = 2131230778;
			
			// aapt resource value: 0x7f08001b
			public const int noSteps = 2131230747;
			
			// aapt resource value: 0x7f08001a
			public const int noThresholds = 2131230746;
			
			// aapt resource value: 0x7f080039
			public const int objects_button = 2131230777;
			
			// aapt resource value: 0x7f080034
			public const int otherComments = 2131230772;
			
			// aapt resource value: 0x7f08000c
			public const int parking = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int parking_invalid = 2131230733;
			
			// aapt resource value: 0x7f080042
			public const int passwordText = 2131230786;
			
			// aapt resource value: 0x7f08000b
			public const int pathes = 2131230731;
			
			// aapt resource value: 0x7f080008
			public const int photo = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int photoFrame = 2131230727;
			
			// aapt resource value: 0x7f080035
			public const int protocolDate = 2131230773;
			
			// aapt resource value: 0x7f08000f
			public const int rampNeeded = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int rampNotNeeded = 2131230734;
			
			// aapt resource value: 0x7f080010
			public const int rampType = 2131230736;
			
			// aapt resource value: 0x7f08003e
			public const int refreshButton = 2131230782;
			
			// aapt resource value: 0x7f08001d
			public const int riffleSurface = 2131230749;
			
			// aapt resource value: 0x7f080043
			public const int savePassword = 2131230787;
			
			// aapt resource value: 0x7f08003b
			public const int save_button = 2131230779;
			
			// aapt resource value: 0x7f08003d
			public const int sendtoser = 2131230781;
			
			// aapt resource value: 0x7f08001c
			public const int stepsHaveRamp = 2131230748;
			
			// aapt resource value: 0x7f080045
			public const int tableRow2 = 2131230789;
			
			// aapt resource value: 0x7f080046
			public const int tableRow3 = 2131230790;
			
			// aapt resource value: 0x7f080048
			public const int text = 2131230792;
			
			// aapt resource value: 0x7f080001
			public const int textView1 = 2131230721;
			
			// aapt resource value: 0x7f080016
			public const int threshold = 2131230742;
			
			// aapt resource value: 0x7f08002b
			public const int wc = 2131230763;
			
			// aapt resource value: 0x7f08002f
			public const int wc_doors_out = 2131230767;
			
			// aapt resource value: 0x7f080030
			public const int wc_inner_handles = 2131230768;
			
			// aapt resource value: 0x7f08002c
			public const int wc_invalid = 2131230764;
			
			// aapt resource value: 0x7f08002e
			public const int wc_invalid_signs = 2131230766;
			
			// aapt resource value: 0x7f08002d
			public const int wc_universal = 2131230765;
			
			// aapt resource value: 0x7f080002
			public const int webAspectButton = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Developer = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Edit1Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Edit2Invalid = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Edit3Entry = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Edit4Lobby = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Edit5Info = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Edit6Hygiene = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Edit7Summary = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int EditItemMainActivity = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int HelpSubActivity = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ItemsSubActivity = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int LoginActivity = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int MainActivity = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int PointItemView = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int dirname = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int CheckBox = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int CustomTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
